### ISSUE TITLE
请问你们用的是什么算力呀？

### ISSUE THREAD

**Issue by Furyboyy** [pengzhiliang/MAE-pytorch#13]
原文用了128核的TPUv3，完全是我企及不到的算力。请问你们用了什么算力啊，我评估一下我手上的算力配不配做预训练

**Comment by pengzhiliang** [comment]
3090/V100

**Comment by Furyboyy** [comment]
多少张呀

**Comment by launchauto** [comment]
> 多少张呀

8卡3090或者V100，单卡batchsiz512, 保证总batchsize是4096就和paper描述的mae-vit-base配置一致。
我这边用了64卡 A100-40G，单卡batchsize 32, 总batchsize4096 mae-beit-base在ImageNet1k上训练了1600个epoch。

**Comment by pengzhiliang** [comment]
有钱人，我只用了8张v100，可以保证batchsize 4096

**Comment by leeyegy** [comment]
请问八卡v100需要跑多久呀

**Comment by leeyegy** [comment]
> > 多少张呀
> 
> 8卡3090或者V100，单卡batchsiz512, 保证总batchsize是4096就和paper描述的mae-vit-base配置一致。 我这边用了64卡 A100-40G，单卡batchsize 32, 总batchsize4096 mae-beit-base在ImageNet1k上训练了1600个epoch。

话说32*64 卡不是batch size只有2048嘛？

**Comment by slchenchn** [comment]
这小batchsize影响大吗？穷人没那么多卡呜呜

**Comment by Pter61** [comment]
卧槽，我这边4卡V100 32G目前还在跑，不知道效果如何。。。
