### ISSUE TITLE
Positional embedding interpolation

### ISSUE THREAD

**Issue by stephenllh** [pengzhiliang/MAE-pytorch#16]
I don't understand these lines of code in the fine-tuning script.
```
num_patches = model.patch_embed.num_patches
num_extra_tokens = model.pos_embed.shape[-2] - num_patches
orig_size = int((pos_embed_checkpoint.shape[-2] - num_extra_tokens) ** 0.5)
```
What is the meaning of extra tokens?
Is there any assumption that the new image size is smaller/larger than the original image size? Same goes for the patch size.

**Comment by pengzhiliang** [comment]
Can you paste a  link to the code you mentioned? I can't find it.

**Comment by pengzhiliang** [comment]
Ok, the code you mentioned will be performed when the `pos_emd` in the checkpoint. However, we use the `sine-cosine` version of positional embedding in our implementation here, which is **unlearnable**. 

But I still can answer this question. `extra_tokens` means the `cls_token`. 
The new image size can be different from the original image size, and the new positional embedding is interpolated from the original positional embedding.

**Comment by stephenllh** [comment]
So, can we (or should we) still implement interpolation if the sine-cosine version is used?

**Comment by pengzhiliang** [comment]
Not necessary.
