### ISSUE TITLE
a small issue in modeling_finetune.py

### ISSUE THREAD

**Issue by Dyfine** [pengzhiliang/MAE-pytorch#17]
Hi, thanks very much for your great repo! Since the current finetuning code doesn't learn a cls token, I think the line below `t = x[:, 1:, :]` will discard the first patch token?

https://github.com/pengzhiliang/MAE-pytorch/blob/40780d61f81a640ef45c39ff238be15b96884a9e/modeling_finetune.py#L277-L281

**Comment by pengzhiliang** [comment]
Yes, you are right. 
Thank you very much!
I will fix it in a minute.

**Comment by pengzhiliang** [comment]
fix it in https://github.com/pengzhiliang/MAE-pytorch/commit/92c23277bb22656525ffe1efd2e321fc4c59d22c
