### ISSUE TITLE
finetune code about cls token

### ISSUE THREAD

**Issue by datuizhuang** [pengzhiliang/MAE-pytorch#19]
Hi, thanks for your great repo! 
you fixed the code:
`# return self.fc_norm(x[:, 1:].mean(1))
return self.fc_norm(x.mean(1))`

but did not fixed the "else" branch, why?(maybe this branch will never been used?)
`return x[:, 0]`

**Comment by pengzhiliang** [comment]
Thanks for your kind words!

> but did not fixed the "else" branch, why?(maybe this branch will never been used?)
Yes, it never been used.

We don't sure how much effect the `cls token` will bring in this repo, so we need to further verify it. (maybe need more time)

In fact, you can delete it.
