### ISSUE TITLE
Could you provide a vpn-free link of pretrained weights rather than Google Drive?

### ISSUE THREAD

**Issue by RayShark** [pengzhiliang/MAE-pytorch#21]
Thanks for your code, I'm poor of GPUs, but I want to make some interesting experements based on MAE.
However, I can't access Google Drive, would you please give a BaiduYun share link of Pretrained Model Weights or some other Cloud Disk without vpn?

Thanks a lot~

**Comment by pengzhiliang** [comment]
Of course. I will add the BaiduYun share link in the next commit.

You can have a try now:
link：https://pan.baidu.com/s/1F0u9WeckZMbNk095gUxT1g 
code：mae6

**Comment by RayShark** [comment]
Got it！
Thank you so much~
