### ISSUE TITLE
Managing 512*512 input size

### ISSUE THREAD

**Issue by HardworkingLittlequ** [pengzhiliang/MAE-pytorch#22]
Thanks for your code! It's really a great work! I want to train MAE on a dataset with 512*512 image size, and how can I adjust the model structure? Thanks for your help.

**Comment by pengzhiliang** [comment]
Thank u for your kind words.
I will try to implement later, because I have a million things to do now.

**Comment by PhoneSix** [comment]
You can register a new model in modeling_pretrain.py and modeling_finetune.py, with parameter 'img_size=512'. Also remember to modify the value of argument named input_size to 512.

**Comment by HardworkingLittlequ** [comment]
Thanks! I'll have a try.

**Comment by pengzhiliang** [comment]
Please feel free to reopen this issue with more info if you are still stuck in this problem.
Thank you！
