### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'in_chans'

### ISSUE THREAD

**Issue by Celestial-Bai** [pengzhiliang/MAE-pytorch#24]
分享一个issue，我一开始用的是11.22更新的requirements.txt，会报如下错误：

File"/MAE-pytorch/modeling_pretrain.py", line 319, in pretrain_mae_base_patch16_224
    **kwargs)
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'in_chans'

我发现好像是timm==0.3.2导致的，后来升至0.4.12可以解决这个问题。
测试了V100 (CentOS) 和 A100 (Ubuntu)，都存在这个issue。
卸载timm好像也一样可以跑……我第一次看CV的code，了解的还不是很多。
顺便想问一下你们在V100选用的batch size是64吗

**Comment by pengzhiliang** [comment]
Ok, Thank you!
I will fix it in a minute.
Total batch size: 4096.

**Comment by Celestial-Bai** [comment]
是不是使用你们给出的command，然后调用8张卡，就可以达到4096的batch size呀？大概是64*8*8=4096？

**Comment by pengzhiliang** [comment]
```bash
# Set the path to save checkpoints
OUTPUT_DIR='output/pretrain_mae_base_patch16_224'
# path to imagenet-1k train set
DATA_PATH='/path/to/ImageNet_ILSVRC2012/train'


# batch_size can be adjusted according to the graphics card
OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=8 run_mae_pretraining.py \
        --data_path ${DATA_PATH} \
        --mask_ratio 0.75 \
        --model pretrain_mae_base_patch16_224 \
        --batch_size 512 \
        --opt adamw \
        --opt_betas 0.9 0.95 \
        --warmup_epochs 40 \
        --epochs 1600 \ # if you need
        --output_dir ${OUTPUT_DIR}
```

**Comment by Celestial-Bai** [comment]
哈哈哈感谢！我们之前很少用--nproc_per_node=8这个command，但是我用V100和A100都set过512，全部炸显存了hhh，不清楚是不是我们服务器调度的问题，非常感谢！

**Comment by Celestial-Bai** [comment]
另外想问一下，你们pre-training使用的外存有多大？不好意思问题有点多了，实在不好意思

**Comment by pengzhiliang** [comment]
It's all right. You're welcome.

When batchsize is set to 512, the GPU memory occupies approximately 30G.

**Comment by Celestial-Bai** [comment]
OK, get it! It is caused by our server. 

And after you update the modeling_pretrain.py, we don't need to upgrade the timm. So you won't need to update the requirements.
Thank you so much for your efforts!
