### ISSUE TITLE
Positional embedding not stored in checkpoints - problem for tuning/inference at higher resolution

### ISSUE THREAD

**Issue by atonderski** [pengzhiliang/MAE-pytorch#26]
Hi,

I'm very impressed with the quick reproduction, nice work!

I have tried running inference with the provided models and noticed that the current checkpoints do not contain the positional embedding. This is not an issue when running on the same resolution (224,224). However, it makes it tricky to run inference at higher resolutions, since there is no positional encoding to interpolate.

I have been using the following hard-coded workaround but as far as I can see, the only solution is to change the model so that the positional encoding is stored as part of the checkpoint. Here is the hard-coded solution for loading current models and running tuning/inference:
```
# this replaces the code from line 334 in run_class_finetuning.py

        # Maybe interpolate position embedding
        old_n_positions = int((224/16)**2)
        if model.pos_embed.shape[1] != old_n_positions:
            embedding_size = model.pos_embed.shape[-1]
            old_pos_embed = modeling_finetune.get_sinusoid_encoding_table(old_n_positions, embedding_size)
            num_patches = model.patch_embed.num_patches
            num_extra_tokens = model.pos_embed.shape[-2] - num_patches
            assert num_extra_tokens == 0, "No support for class tokens"
            # height (== width) for the checkpoint position embedding
            orig_size = int((old_pos_embed.shape[-2] - num_extra_tokens) ** 0.5)
            # height (== width) for the new position embedding
            new_size = int(num_patches ** 0.5)
            # class_token and dist_token are kept unchanged
            if orig_size != new_size:
                print("Position interpolate from %dx%d to %dx%d" % (orig_size, orig_size, new_size, new_size))
                extra_tokens = old_pos_embed[:, :num_extra_tokens]
                # only the position tokens are interpolated
                pos_tokens = old_pos_embed[:, num_extra_tokens:]
                pos_tokens = pos_tokens.reshape(-1, orig_size, orig_size, embedding_size).permute(0, 3, 1, 2)
                pos_tokens = torch.nn.functional.interpolate(
                    pos_tokens, size=(new_size, new_size), mode='bicubic', align_corners=False)
                pos_tokens = pos_tokens.permute(0, 2, 3, 1).flatten(1, 2)
                new_pos_embed = torch.cat((extra_tokens, pos_tokens), dim=1)
                model.pos_embed = new_pos_embed
```

**Comment by pengzhiliang** [comment]
Thank you for your affirmation！

As you know, we use the sine-cosine positional embedding mentioned in the paper. And those are not learnable parameters, and are not stored in checkpoints.  So a potential solution is to use the learnable positional embedding.

And if you run it at higher resolutions here, you maybe not need to interpolate the sine-cosine positional embedding.
Because `get_sinussoid_encoding_table` function can return a given number of positional embedding, you only need to change the corresponding parameters.

**Comment by pengzhiliang** [comment]
Please feel free to reopen this issue with more info if you are still stuck in this problem.
Thank you！

**Comment by atonderski** [comment]
Hi, sorry for the slow response. 

I agree that the sine-cosine embeddings are not learnable. However it seems like they still need to be interpolated for the model to work well. I suspect that this is at least partially due to the fact that they are 1d, and thus the model has to learn the number of rows/column. E.g. it cannot say "look one patch down" but rather has to say "look X patches forward".

I have attached attention visualizations that show what happens if you run on higher res with or without interpolating the positional embedding. As  you can see, the non-interpolated version looks worse and has weird diagonal stripes. 

This is not a big issue to me, but I wanted to let you (and anyone else that has the same problem) know about this. I think the best solution is what I mentioned before: to simply include the positional embeddings in the checkpoint even though they are not learnable parameters.

<img width="1083" alt="with_interp" src="https://user-images.githubusercontent.com/7511830/144020865-01332fc6-0838-4761-8e54-b599191d5b8d.png">
<img width="1082" alt="original_res" src="https://user-images.githubusercontent.com/7511830/144020873-64049ce3-70e1-4304-8a58-d8385297ea0e.png">
<img width="1095" alt="without_interp" src="https://user-images.githubusercontent.com/7511830/144020848-587393ed-84b0-43c7-8ed7-9f2741b07f7a.png">

**Comment by cliangyu** [comment]
@atonderski Could you please share how to draw the self-attention map, without class token?

**Comment by atonderski** [comment]
Yeah, so since there is no class token I am here visualising the attention map of an arbitrarily picked token (signified by the red dot in the image. There are of course as many attention maps as there are token/patches

**Comment by cliangyu** [comment]
There are 12 images... are they corresponding to 12 heads?
Do you mind pushing the code? Thank you!
