### ISSUE TITLE
timm model中找不到pretrain_mae_base_patch16_224 模型registry

### ISSUE THREAD

**Issue by maoxiaofei99** [pengzhiliang/MAE-pytorch#30]
hello，timm model中找不到pretrain_mae_base_patch16_224 模型registry，pretrain_mae_base_patch16_224 和 PretrainVisionTransformer是怎么映射的呢？

**Comment by zongzi13545329** [comment]
你需要在run_xxxx中import modeling_pretrain / modeling_finetune

**Comment by maoxiaofei99** [comment]
> 
明白了，非常感谢喔～

**Comment by pengzhiliang** [comment]
https://github.com/pengzhiliang/MAE-pytorch/blob/3546179ac5c4f0b80918b79f68678a42c8719808/run_mae_pretraining.py#L27
