### ISSUE TITLE
EMA evaluation does not use the exponential moving avera

### ISSUE THREAD

**Issue by wangqingbin** [pengzhiliang/MAE-pytorch#31]

**Comment by wangqingbin** [comment]
when training, using the ema_model.update() methods to keep the model ema parameters, but when invoke the evaluate() method, the code just uses the model parameters, whether I missing some useful code, could you explain it? I am very confused.

**Comment by pengzhiliang** [comment]
I am sorry that I do not notice it before. 
But I think it does not matter because it's just a trick.
Maybe EMA weight can achieve a little better performance.

As you see, you can choose to load the EMA weight in the checkpoint to have a try.

Thank you!
