### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'

### ISSUE THREAD

**Issue by DDxk369** [pengzhiliang/MAE-pytorch#32]
您好，
        感谢您提供的这个工作， 非常棒，但是当我尝试运行run_class_finetuning.py时，出现报错TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'
请问该如何解决，谢谢

**Comment by PhoneSix** [comment]
能把完整的报错信息贴一下吗，方便我们定位问题。初步猜测可能是你timm版本不对，你也可以看看是不是这个原因导致的，我们这边儿是可以跑通的

**Comment by pengzhiliang** [comment]
Please feel free to reopen this issue with more info if you are still stuck in this problem.
Thank you！

**Comment by DDxk369** [comment]
您看下 ，这是完整报错：
C:\Users\asus\anaconda3\python.exe C:/Users/asus/PycharmProjects/classification-pytorch/MAE/run_class_finetuning.py
Not using distributed mode
Namespace(aa='rand-m9-mstd0.5-inc1', attn_drop_rate=0.0, auto_resume=True, batch_size=64, clip_grad=None, color_jitter=0.4, crop_pct=None, cutmix=1.0, cutmix_minmax=None, data_path='C:\\Users\\\\asus\\PycharmProjects\\classification-pytorch\\Lung_newrefined_data', data_set='IMNET', device='cuda', disable_eval_during_finetuning=False, dist_eval=False, dist_on_itp=False, dist_url='env://', distributed=False, drop=0.0, drop_path=0.1, enable_deepspeed=False, epochs=30, eval=False, eval_data_path='C:\\Users\\\\asus\\PycharmProjects\\classification-pytorch\\Lung_newrefined_data', finetune='', imagenet_default_mean_and_std=True, init_scale=0.001, input_size=224, layer_decay=0.75, local_rank=-1, log_dir=None, lr=0.001, min_lr=1e-06, mixup=0.8, mixup_mode='batch', mixup_prob=1.0, mixup_switch_prob=0.5, model='deit_base_patch16_224', model_ema=False, model_ema_decay=0.9999, model_ema_force_cpu=False, model_key='model|module', model_prefix='', momentum=0.9, nb_classes=3, num_workers=10, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='', pin_mem=True, recount=1, remode='pixel', reprob=0.25, resplit=False, resume='', save_ckpt=True, save_ckpt_freq=20, seed=0, smoothing=0.1, start_epoch=0, train_interpolation='bicubic', update_freq=1, use_mean_pooling=True, warmup_epochs=5, warmup_lr=1e-06, warmup_steps=-1, weight_decay=0.05, weight_decay_end=None, world_size=1)
Transform = 
RandomResizedCropAndInterpolation(size=(224, 224), scale=(0.08, 1.0), ratio=(0.75, 1.3333), interpolation=PIL.Image.BICUBIC)
RandomHorizontalFlip(p=0.5)
<timm.data.auto_augment.RandAugment object at 0x0000025B86DC9190>
ToTensor()
Normalize(mean=tensor([0.4850, 0.4560, 0.4060]), std=tensor([0.2290, 0.2240, 0.2250]))
<timm.data.random_erasing.RandomErasing object at 0x0000025B86DC3BE0>
---------------------------
C:\Users\asus\anaconda3\lib\site-packages\torchvision\transforms\transforms.py:257: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Number of the class = 3
Transform = 
Resize(size=256, interpolation=bicubic)
CenterCrop(size=(224, 224))
ToTensor()
Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
---------------------------
Traceback (most recent call last):
  File "C:/Users/asus/PycharmProjects/classification-pytorch/MAE/run_class_finetuning.py", line 513, in <module>
    main(opts, ds_init)
  File "C:/Users/asus/PycharmProjects/classification-pytorch/MAE/run_class_finetuning.py", line 284, in main
    model = create_model(
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\factory.py", line 81, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\vision_transformer.py", line 819, in deit_base_patch16_224
    model = _create_vision_transformer('deit_base_patch16_224', pretrained=pretrained, **model_kwargs)
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\vision_transformer.py", line 537, in _create_vision_transformer
    model = build_model_with_cfg(
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\helpers.py", line 445, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'
Number of the class = 3

**Comment by DDxk369** [comment]
您看下 完整的报错：

Resize(size=256, interpolation=bicubic)
CenterCrop(size=(224, 224))
ToTensor()
Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
Traceback (most recent call last):
  File "C:/Users/asus/PycharmProjects/classification-pytorch/MAE/run_class_finetuning.py", line 513, in <module>
    main(opts, ds_init)
  File "C:/Users/asus/PycharmProjects/classification-pytorch/MAE/run_class_finetuning.py", line 284, in main
    model = create_model(
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\factory.py", line 81, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\vision_transformer.py", line 819, in deit_base_patch16_224
    model = _create_vision_transformer('deit_base_patch16_224', pretrained=pretrained, **model_kwargs)
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\vision_transformer.py", line 537, in _create_vision_transformer
    model = build_model_with_cfg(
  File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\helpers.py", line 445, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
**TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'**
Number of the class = 3
Sampler_train = <torch.utils.data.distributed.DistributedSampler object at 0x0000025B86DABAF0>
Mixup is activated!

**Comment by PhoneSix** [comment]
> File "C:\Users\asus\PycharmProjects\classification-pytorch\timm\models\helpers.py", line 445, in build_model_with_cfg
model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: init() got an unexpected keyword argument 'use_mean_pooling'
如报错信息所示，应该是timm版本的问题，你装一下0.4.12的版本试试
`pip install timm==0.4.12`

**Comment by MingfangDeng** [comment]
I have the same problem,and use the version of timm is also 0.4.12,but the problem is still unsolved.

**Comment by Lukangkang123** [comment]
I also have the same problem,and My timm is also 0.4.12

**Comment by AnwarKhanniazi** [comment]
File "/usr/local/lib/python3.7/dist-packages/timm/models/helpers.py", line 445, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'

**Comment by AnwarKhanniazi** [comment]
how solve this issue?
 File "/usr/local/lib/python3.7/dist-packages/timm/models/helpers.py", line 445, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'

**Comment by ckmessi** [comment]
I encountered this problem.

The root cause is that **the ViT model structure is chosen incorrectly**. The `use_mean_pooling` property is defined in the `VisionTransformer` class located in `modeling_finetune.py`. If you run the `run_class_finetuning.py` without changing the `--model` arguments, it will load the default `deit_base_patch16_224` model structure who has no such property.

So the solution is add the argument `--model vit_base_patch16_224` or other models defined in `modeling_finetune.py`.

**Comment by Pumpkinder** [comment]
add "import modeling_finetune" sovle the problem
