### ISSUE TITLE
Can you provide the organization of the dataset

### ISSUE THREAD

**Issue by shandong-university-weihai-chen** [pengzhiliang/MAE-pytorch#37]
Can you provide the organization of the data set
such as:
![2020052623312390](https://user-images.githubusercontent.com/62422590/144001143-ffd109e1-58f0-44e7-aeea-419bb42b74ce.jpeg)

**Comment by pengzhiliang** [comment]
Hello.
Your sketch is very realistic.

The training and validation data is expected to be in the train/ folder and val folder respectively:
```bash
/path/to/imagenet/
  train/
    class1/
      img1.jpeg
    class2/
      img2.jpeg
  val/
    class1/
      img3.jpeg
    class/2
      img4.jpeg
```
