### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by YhVincent** [pengzhiliang/MAE-pytorch#4]
Thanks a lot for the code!
However, I only have 4 GPUS. And it may cost me about 33 days to get the Vit-Large pretrained model.
Would you mind uploading the pretrained model? Or the Vit-base pretrained model will be appreciated.

**Comment by pengzhiliang** [comment]
Thank you for your kind words~
I can publish the pretrained vit-base model later, or even vit-small. And I also don't have enough gpus to pretrain vit-large.

**Comment by pengzhiliang** [comment]
See https://github.com/pengzhiliang/MAE-pytorch/issues/5#issuecomment-973822378
