### ISSUE TITLE
hello, a little question about this code.

### ISSUE THREAD

**Issue by thebestYezhang** [pengzhiliang/MAE-pytorch#41]
I am beginner and crazy about this MAE, but about the pretrained model--_**pretrain_mae_vit_base_mask_0.75_400e.pth**_ downloaded from BaiDu yun, I really wanna know where to load it in the file. Can it be used in modeling_pretrain.py?

**Comment by pengzhiliang** [comment]
Yes, maybe the visualization is a good start.

**Comment by thebestYezhang** [comment]
不好意思，我没懂您的意思。是这样的，我想加载你们的MAE训练好的模型，也就是pretrain_mae_vit_base_mask_0.75_400e.pth这个权重。然后取出encoder部分进行finetune，然后去做我的分类任务，这样子应该怎么操作呢？指导一下，感激不尽！！！

**Comment by pengzhiliang** [comment]
Ok. You can fine tune it on your dataset.
Please reference: run_class_finetuning.py

**Comment by zsddd** [comment]
> 不好意思，我没懂您的意思。是这样的，我想加载你们的MAE训练好的模型，也就是pretrain_mae_vit_base_mask_0.75_400e.pth这个权重。然后取出encoder部分进行finetune，然后去做我的分类任务，这样子应该怎么操作呢？指导一下，感激不尽!!!

你好，请问你这个分类任务成功的吗？可否提供下代码，感谢
