### ISSUE TITLE
the problem of imagenet datasets

### ISSUE THREAD

**Issue by MingfangDeng** [pengzhiliang/MAE-pytorch#42]
Hi,firstly congradulate you!
However,the imagenet has too many pictures,I cannot choose which one.
can you tell me the details of datasets? it's better to upload baiduDisk or Drive.
thank you!

**Comment by pengzhiliang** [comment]
Ok, thank you~

More information about imagetnet1k can refer to [here](https://image-net.org/challenges/LSVRC/2012/index#introduction).

Upload such a big data set is also a challenge for us. 
You can also find some available netdisk(like baiduyun and google drive) links in some blogs.
Good luck!
