### ISSUE TITLE
Why use ema in finetuning?

### ISSUE THREAD

**Issue by obiyoag** [pengzhiliang/MAE-pytorch#43]
Thanks for your great work! 
I am confused that I don't think the authors mention ema in their paper but I find it in your implementation. Could you explain why you use that? And is it OK for me not to use it?

**Comment by pengzhiliang** [comment]
Thank u！
Yes, I inherit EMA from the BEIT code but don't use it. 
You can have a check in [here](https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/run_class_finetuning.py?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L58)
