### ISSUE TITLE
help

### ISSUE THREAD

**Issue by huanghaiyun-ui** [pengzhiliang/MAE-pytorch#44]
Hello, I'm a novice. I want to ask. Download directly ImageNet_ILSVRC2012 dataset, can you get the pre training model according to your pre train process? If not, how can I get it. Can two GPUs pre train themselves?

**Comment by pengzhiliang** [comment]
Of course you can. But it may take a long time to finish it with two gpus.

**Comment by huanghaiyun-ui** [comment]
thanks😂



---Original---
From: "Zhiliang ***@***.***&gt;
Date: Thu, Dec 2, 2021 23:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pengzhiliang/MAE-pytorch] help (Issue #44)




 
Of course you can. But it may take a long time to finish it with two gpus.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huanghaiyun-ui** [comment]
Hello, I downloaded the Imagenet dataset ILSVRC2012_image_train.tar. Can I run the tar package directly under the specified path? Do you need any other operations?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pengzhiliang/MAE-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 晚上11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pengzhiliang/MAE-pytorch] help (Issue #44)





 
Closed #44.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanng-ide** [comment]
I  want to know how to process the dataset, too....
There are a lot of tar files.

Is there any commands or processing file?
It is my firtst time to do this....

Sorry for my stupid question..
