### ISSUE TITLE
the problem of result

### ISSUE THREAD

**Issue by MingfangDeng** [pengzhiliang/MAE-pytorch#45]
I'm sorry to interrupt you again and appreciate the previous helps. And the program has been run.But the result is not good.I choose the datasets which are created by me.I want ti know if I choose the large datasets the result will be better？And I find the patch size you set is 16*16，if I choose smaller like 6*6，can it will be better and more clear?
thank you for your attention. @pengzhiliang

**Comment by pengzhiliang** [comment]
Sorry for the late reply.

> But the result is not good. I choose the datasets which are created by me.

Is this dataset to be used to be pre-training or fine-tuning?
If for pre-training, I think the scale of dataset is still an important factor. So the large dataset can bring more gains.
If for fine-tuning, maybe a group suitable hyperparameters is all you need. 

As for patch-size, I am sorry that I have no idea to answer you.

Thank you for your support and please feel free to reopen this issue or open a new one if you need!
