### ISSUE TITLE
A little question about the visualization

### ISSUE THREAD

**Issue by Dou-Yiming** [pengzhiliang/MAE-pytorch#46]
Hi, thanks a lot for the excellent work!!

When I executed run_mae_vis.py, there is a strange phenomenon that the model is able to reconstruct the origin img without lossing much information even if only one patch is given.

As shown in the following example, the mask_ratio is set as 0.999, making sure that the model can only get one patch. However, it is really strange to find out that the model can almost reconstruct the origin img (e.g. the shape of the bird, the yellow feather...)

I think it is impossible for the model to do this. Therefore, may I ask whether there is some information of the origin img other than the visible patch that is sent into the model? Really looking forward to your reply! Thanks!
![image](https://user-images.githubusercontent.com/62940175/144698837-0130b4e8-7035-4f28-a720-84d4f6738ea6.png)

**Comment by Dou-Yiming** [comment]
Oh, I've found the reason mentioned in Issue 40, sorry for interrupting!

**Comment by huanghaiyun-ui** [comment]
I wonder, too
