### ISSUE TITLE
Why don't train the k_bias 

### ISSUE THREAD

**Issue by slchenchn** [pengzhiliang/MAE-pytorch#52]
Hi, I found that the `k_bias` of every attention layer is set as not requiring gradient, while the `q_bias` and `v_bias` do require gradient, see the [code](https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/modeling_finetune.py#L91)

Is there any reason behind this? Since all the biases are set to learnable in common implementations.

**Comment by liyz15** [comment]
Check this https://github.com/microsoft/unilm/issues/510

**Comment by slchenchn** [comment]
> Check this [microsoft/unilm#510](https://github.com/microsoft/unilm/issues/510)

thanks!
