### ISSUE TITLE
How to process the dataset...

### ISSUE THREAD

**Issue by wanng-ide** [pengzhiliang/MAE-pytorch#53]
I want to know how to process the dataset....
There are a lot of tar files.

Is there any commands or processing python file?
It is my firtst time to do this....

Sorry for my stupid question..

**Comment by pengzhiliang** [comment]
Take it easy.

You can use this dataset provided in timm [here](https://github.com/rwightman/pytorch-image-models/blob/f7d210d759beb00a3d0834a3ce2d93f6e17f3d38/timm/data/dataset.py?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L20), which can directly read .tar files.

**Comment by wanng-ide** [comment]
> Take it easy.
> 
> You can use this dataset provided in timm [here](https://github.com/rwightman/pytorch-image-models/blob/f7d210d759beb00a3d0834a3ce2d93f6e17f3d38/timm/data/dataset.py?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L20), which can directly read .tar files.

Thank you !!

**Comment by wanng-ide** [comment]
@pengzhiliang Sorry to disturb you.
I meet a problem.

RuntimeError: Found 0 files in subfolders of: "data/ImageNet/val"
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp

It is a  subprocess.CalledProcessError.

However, I already put my val images in the  "data/ImageNet/val" folder.

![image](https://user-images.githubusercontent.com/32323900/146332012-afa3c2ad-033f-47a1-825a-1c17b72508cf.png)
![image](https://user-images.githubusercontent.com/32323900/146332050-4674f28e-426a-43cf-8e24-cbbd2181605c.png)

How is that possible...

**Comment by wanng-ide** [comment]
The pretraining codes are fine.
However, the finetune codes are not work .....
