### ISSUE TITLE
How about change encoder and decoder to transformer variants

### ISSUE THREAD

**Issue by Dreamer312** [pengzhiliang/MAE-pytorch#54]
Hi,

我想试试换成swin transformer，那是不是mask token只在第一layer 替换到图片token里面比较合理

**Comment by pengzhiliang** [comment]
Uh, You can have a try.

**Comment by Xinxinatg** [comment]
> 

打扰一下，你有预训练出swin transformer吗？

**Comment by Dreamer312** [comment]
不用试了，微软自己换了。simmim
