### ISSUE TITLE
Where to place the ImageNet2012 images tar file and anotations tar file?

### ISSUE THREAD

**Issue by miznchimaki** [pengzhiliang/MAE-pytorch#57]
Hello! I download the ILSVRC2012 dataset, my ILSVRC2012 dataset root directory is:`path/to/ILSVRC012`. Images and annotations tar files are all in the above directory. All tar files are listed below:
`ILSVRC2012_img_train.tar`
`ILSVRC2012_img_val.tar`
`ILSVRC2012_bbox_train_v2.tar.gz`
`ILSVRC2012_bbox_val_v3.tgz`
I want to know is it ok to place all those four files in the dataset root directory? Otherwise what should I do to preprocess these four tar files?
Thanks very much!

**Comment by pengzhiliang** [comment]
Hello, you just need to uncompress them.

**Comment by pengzhiliang** [comment]
Please feel free to reopen this issue~
