### ISSUE TITLE
Results about different pretrain epochs.

### ISSUE THREAD

**Issue by ggjy** [pengzhiliang/MAE-pytorch#59]
Hi, thanks for your great work. When I try to reproduce the results, I find that three ```mae_vit_base``` pretrained in 200/400/800 epochs get similar final finetune result (100 epochs) 83.06/83.07/83.02. Do you encounter the same situation?

**Comment by pengzhiliang** [comment]
Hello, thank you for your report.
I have not do many experiments with different pretrained epochs. 

But others report it with ViT-L on this repo:
* pre-trained 400e + fine-tuned 50e: 84.5%
* pre-trained 800e + fine-tuned 50e: 85.1%

**Comment by pengzhiliang** [comment]
In fact, as far as I know, pre-training with 100e also can reach high performance.

**Comment by ggjy** [comment]
Thanks for you kindly reply.
