### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_mean_pooling'

### ISSUE THREAD

**Issue by Lukangkang123** [pengzhiliang/MAE-pytorch#60]
My timm version is 0.4.12, which is same as your timm version in  requirements.txt. So why  I met this problem? and How can I sovle this problem?
![sendpix1](https://user-images.githubusercontent.com/38984189/145986101-33b23960-15ba-477c-a225-5ca396a89691.jpg)

**Comment by pengzhiliang** [comment]
Have you modified the code? Can you show your command?

**Comment by pengzhiliang** [comment]
Oh, it seems that your model name is `deit_base_patch16_224`, which is wrong.
You can change it to `vit_base_patch16_224`
![image](https://user-images.githubusercontent.com/26346329/146006086-fb9247d4-a3e0-4267-acfa-977cf77f6eaf.png)

**Comment by Lukangkang123** [comment]
I will try it later, thanks you
