### ISSUE TITLE
Can you create this model to timm?

### ISSUE THREAD

**Issue by Lukangkang123** [pengzhiliang/MAE-pytorch#63]
Thanks for your implementation of MAE, which help me a lot. But your code is so sophisticated that I can't understand it all. More importantly,  I can't directly to use it to my dowmstream task. Therefore,  I wanna to ask you whether you can create this model to timm  or not(such as  "timm.create_mode('pretrain_mae_base_patch16_224', pretrained=True)" . Thanks a lot .

**Comment by pengzhiliang** [comment]
Emmm, good suggestion! But it is not in my schedule.
