### ISSUE TITLE
how much time be consumed in your pretraining???

### ISSUE THREAD

**Issue by chenxl124578** [pengzhiliang/MAE-pytorch#66]
this is the first time i making some research about self-supervise. But i consume 1 hour per epoch when i pretraining (about 20k samples in one epoch),  i don't know  whether i pretrain correctly, i think it may be train too fast and it is normal to consume 4 hours to pretrain an epoch. Did anyone can tell me how much time be consumed in your pretraining? Thanks a lot!

**Comment by pengzhiliang** [comment]
It's normal. Because the input visible patches is only 25% of input images. And the decoder has <10% computation per token vs. the encoder. 
You can find those in the paper.

**Comment by cyy53589** [comment]
Hi, thanks for your great job.
I wonder which GPU you guys are using? pengzhiliang memtioned that 3090/A100, but I still wonder how many is enough? I use a single 2080 and it seemed running a little slow( 8 hours on ~4K image / epoch). 
Thanks a lot!
