### ISSUE TITLE
mask是如何生成的？

### ISSUE THREAD

**Issue by DyCheer** [pengzhiliang/MAE-pytorch#68]
https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/modeling_pretrain.py#L101

我猜测变量mask是从masking_generator.py的RandomMaskingGenerator里生成的，但是我找到这个类在哪里被调用了？

**Comment by pengzhiliang** [comment]
[here](https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/datasets.py#L41)
