### ISSUE TITLE
Mask's format

### ISSUE THREAD

**Issue by DISAPPEARED13** [pengzhiliang/MAE-pytorch#69]
Thanks for implementation of the paper! Respect!
And I am a new comer for MAE, I am working on re-generating masked image and I want to ask that:
what's the mask format in this code? a bool tensor like (B, input_size*input_size)? seems define in pixels.
and how can I modify a special mask for my own image? 
Thank you!

Best,
D

**Comment by DISAPPEARED13** [comment]
when code run to `x_vis = x[~mask].reshape(B, -1, C)` ,things went wrong. I think that mask should be the same size with image? it that? 
I customize my own mask just for set the bounding box to **True** and the other **pixels** to **False**. It's that right?

Best,
D

**Comment by pengzhiliang** [comment]
Hello, sorry for the late reply.

The initial mask comes from [here](https://github.com/pengzhiliang/MAE-pytorch/blob/8b3ab30f99000ac56b2469de6fd48341ed799a21/masking_generator.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L29):
```python
mask = np.hstack([
            np.zeros(self.num_patches - self.num_mask),
            np.ones(self.num_mask),
        ])
```
which implies that the mask is based on the tokens not on the pixels.

Of course, the mask based on the pixel is no problem. But you should reshape the mask to match the shape of input image tokens.
