### ISSUE TITLE
ViT-Small

### ISSUE THREAD

**Issue by DRSY** [pengzhiliang/MAE-pytorch#7]
Any plan to pre-train a ViT-Small version?

**Comment by pengzhiliang** [comment]
Sure, wait a minute.

**Comment by pengzhiliang** [comment]
Actually, I have trained the vit-small 400e, and then performed end-to-end finetuning 100e. But it only reaches 78.82%, so I am not sure it works or not.

**Comment by DTennant** [comment]
Hi, Thanks for the code.
May I ask how long does it to train a vit-small for 400e?
And what kind of graphic cards are you using to train

**Comment by pengzhiliang** [comment]
You can try to run it, and then you can get the answer.

**Comment by Darren-dagong** [comment]
> Actually, I have trained the vit-small 400e, and then performed end-to-end finetuning 100e. But it only reaches 78.82%, so I am not sure it works or not.

how to edit code for end-to-end finetuning? THX
