### ISSUE TITLE
About the positional embedding.

### ISSUE THREAD

**Issue by InfinityBox** [pengzhiliang/MAE-pytorch#72]
Hi! Thank you for your contribution!

I'm just wondering about the difference between using unlearnable positional embedding and learnable positional embedding in this paper? 

Thank you very much!

**Comment by pengzhiliang** [comment]
Hello, I have not performed this ablation.

You can have a try among 1-D sine-cosine, 2-D sine-cosine and learnable pos embeddings, if you are interested.

And if you have the results, welcome to report it here.
