### ISSUE TITLE
Could you add a fine-tuned ViT-B model?

### ISSUE THREAD

**Issue by Freder-chen** [pengzhiliang/MAE-pytorch#74]
I want to use this weight, but it takes a long time to train by myself.

**Comment by pengzhiliang** [comment]
You can check it in the [RESULT](https://github.com/pengzhiliang/MAE-pytorch/blob/main/README.md#result) session in [README](https://github.com/pengzhiliang/MAE-pytorch/blob/main/README.md)

**Comment by Freder-chen** [comment]
But I only saw the pre-trained weights. Fine-tuned ViT-B only has log.

**Comment by Freder-chen** [comment]
> check

But I only saw the pre-trained weights. Fine-tuned ViT-B only has log.

**Comment by pengzhiliang** [comment]
I'm sorry, I misremembered.

And I will add this link as soon as possible!

**Comment by pengzhiliang** [comment]
BaiduYun: 
link: https://pan.baidu.com/s/154dFv0uCOQPZCpQvcim89Q 
code: mae6

**Comment by Freder-chen** [comment]
> BaiduYun: link: [https://pan.baidu.com/s/154dFv0uCOQPZCpQvcim89Q ](https://pan.baidu.com/s/154dFv0uCOQPZCpQvcim89Q%C2%A0) code: mae6

Thanks
