### ISSUE TITLE
ILSVRC2012-dataset

### ISSUE THREAD

**Issue by xiyufeng2** [pengzhiliang/MAE-pytorch#76]
hello,author!  I have download ILSVRC2012 dataset but the annotation file can't be uesed directly. Can you share it to my Emeil?Thank you!
作者你好，我下载了ILSVRC2012数据集，但是标注是caffe格式，没法转成python的。您能将标注文件分享给我吗？万分感谢！邮箱：496598212@qq.com

**Comment by pengzhiliang** [comment]
Hello~
I am sorry that I have no label files. My dataset is organized as:
https://github.com/pengzhiliang/MAE-pytorch/issues/79#issuecomment-1004480327
