### ISSUE TITLE
A little suggestion about data 

### ISSUE THREAD

**Issue by wangning7149** [pengzhiliang/MAE-pytorch#79]
Thank you for your contribution！！
Can I make a suggestion? Can this path be created?  "/path/to/ImageNet_ILSVRC2012",  you only need to put a few pictures and labels inside. In this way, everyone can run quickly and learn the code better. Thanks ! !

**Comment by pengzhiliang** [comment]
OK, thanks for your kind suggestion!

the dataset format can reference to:

https://github.com/pengzhiliang/MAE-pytorch/issues/37#issuecomment-982702706
