### ISSUE TITLE
the config

### ISSUE THREAD

**Issue by yyl199655** [pengzhiliang/MAE-pytorch#8]
hello, 
You have trained a total of 400 epochs, the parameter configuration is set to 1600, and then you took the 400th epoch model, or you directly set --epochs to 400

**Comment by pengzhiliang** [comment]
directly set --epochs to 400

**Comment by yyl199655** [comment]
Have other parameters changed？？

**Comment by pengzhiliang** [comment]
Not yet. You can check it with the paper.
