### ISSUE TITLE
A warning when pretraining

### ISSUE THREAD

**Issue by peiyingxin** [pengzhiliang/MAE-pytorch#84]
when i pretraining using ImageNet-1K from scratch，sometimes i got a warning：

/opt/conda/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Corrupt EXIF data.  Expecting to read 2 bytes but only got 0. 
  warnings.warn(str(msg))
/opt/conda/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:771: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 2. Skipping tag 41487
  warnings.warn(

someone know about this warning？and it will make an impact on pretraining？
thanks a lot~

**Comment by pengzhiliang** [comment]
Hello~
This is an error caused by loading some images.
And it make no impact on pt.
There should be nothing to be concerned about.

**Comment by peiyingxin** [comment]
> Hello~ This is an error caused by loading some images. And it make no impact on pt. There should be nothing to be concerned about.

Hi,
when got this loading images error,  will it skip this image and load the next image？
